CREATE DATABASE projeto_clinicas_nara;

USE projeto_clinicas_nara;

CREATE TABLE Clinicas(
	ID_CLINICA INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100),
    Cidade VARCHAR(50),
    CAPACIDADE_DIARIA INT);

LOAD DATA INFILE 'C:/Users/cmjfe/Documents/Projeto-Final-SENAC/clinicas.csv' # CARREGAMENTO DE ARQUIVO
INTO TABLE Clinicas
FIELDS TERMINATED BY ',' #INFORMANDO QUE O SEPARADOR É VIRGULA
LINES TERMINATED BY '\n' #INSERIR QUEBRA DE LINHA AO FINAL DE CADA LINHA
IGNORE 1 ROWS; #IGNORAR PRIMEIRA LINHA, QUE NESSE CASO SERÁ O CABECALHO

SHOW VARIABLES LIKE 'secure_file_priv';

SELECT * FROM Clinicas;